database:
  host: "localhost"
  port: "5432"
  user: "otus"
  password: "otus"
  name: "calendar"

app:
  host: "127.0.0.1"
  port: "8000"
  type: "local"

grpc:
  host: "127.0.0.1"
  port: "50051"

logging:
  path: "."
  loglevel: "debug"